### ISSUE TITLE
Advantages and Disadvantages do not properly save

### ISSUE THREAD

**Issue by diogosalazar83** [polepage/L5R_NPCTool#11]
When you assign a new advantage or disadvantage to a NPC, they won't be saved properly (only the name and Ring will show up, not the skills or sphere) if you add or change something else like gear.

**Comment by polepage** [comment]
I think it is specifically when you add something that was already saved (like adding an item from the saved items by opposition to creating a new one from scratch in the NPC sheet).

Workaround: Do the Advantages and Disadvantages last.

I will look into it more closely now that I have a user that is not me ;)

**Comment by diogosalazar83** [comment]
Yes, I've been doing that workaround, and C# is not my strongest suit, otherwise I would be glad to help. I am more of a Java developer.

**Comment by polepage** [comment]
So adding an object don't seem to be an issue. It's badly tagged, so I think the fix has just not been put in the available version on google drive. However there is the issue that opening a new tab (either from the rightside menu or by using the "Open in a new tab" button in the character sheet) clears the skills and sphere on all opened characters sheets. It also clear them "cleanly" because the character tabs show they are modified and can be closed without saving without losing the parameters. I'll look into that.

**Comment by polepage** [comment]
Issue has been found. It appears that WPF TabControl reuse the same tab. So when changing tab, the controls that hold Skills and Spheres are reset. Because of some arcane hell of my own making, the modification is descended down to data before the change of tab, so the values are cleared.

Next step will be to investigate a solution to that specific issue.

**Comment by polepage** [comment]
TabControl no longer reuse tabs. It makes the Advantages and Disadvantages lose traits because of that reuse. There may be performance issues if A LOT of tabs are open at the same time, but I guess it must be a lot. Fixed in release 1.2.

**Comment by diogosalazar83** [comment]
That's awesome. Thanks
